ecom/urls.py
from django.urls import path
from ecom.views import *

app_name ='ecom'

urlpatterns = [
path('',HomeView.as_view(), name='home'),
path('create_new_category',CategoryCreateView.as_view(), name='categorycreate')
]

library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('user.urls')),
    path('',include('ecom.urls'))
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user.views import *

app_name='user'
urlpatterns = [
    # path('signup', signup, name='signup'),
    path('signup', SignupView.as_view(), name='signup'),
    # path('login', login_user, name='login'),
    path('login', SignInView.as_view(), name ='login'),
    path('logout', SignOutView.as_view(), name='logout')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Sign Up Form</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="{% static 'bootstrap-5.3.0-alpha1-dist/css/bootstrap.min.css' %}"
    />
  </head>
  <body>
   
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/contact"
        ><img
          style="height: 50px; width: 50px; border-radius: 50%"
          src="{% static 'images/logo.png' %}"
        />
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupzportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact us</a>
          </li>
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/users/login">Sigin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/signup">Sign up</a>
          </li>
          {% else %}
          <li class="nav-item">Welcome {{request.user}}</li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:logout' %}">log out</a>
          </li>

          {% endif %}
        </ul>
      </div>
    </nav>
    {% if messages %} {% for message in messages %}
    <div
      class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}"
      role="alert"
    >
      {{ message }}
    </div>
    {% endfor %} {% endif %}
    {% block content %} {% endblock content%}
    <script src="{% static 'bootstrap-5.3.0-alpha1-dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>